import nodemailer from 'nodemailer';

export default async function handler(req, res) {
  // Allow CORS
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    const { type, orderData } = req.body;

    if (!orderData) {
      return res.status(400).json({ error: 'orderData is required' });
    }

    const gmailUser = process.env.GMAIL_USER || process.env.VITE_GMAIL_USER || 'madsruzza@gmail.com';
    const gmailPass = process.env.GMAIL_APP_PASSWORD || process.env.VITE_GMAIL_APP_PASSWORD || 'bcmfyxbytinwmlzm';

    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: gmailUser,
        pass: gmailPass
      }
    });

    let subject = '';
    let htmlContent = '';
    let recipient = '';

    if (type === 'admin_alert') {
      recipient = 'admin@lyntrix.tech, ' + gmailUser;
      subject = `🚀 [NEW ORDER INQUIRY] Proposal ${orderData.id} - ${orderData.name} (${orderData.service})`;
      htmlContent = `
        <div style="font-family: Arial, sans-serif; background-color: #07090e; color: #f1f5f9; padding: 30px; max-width: 600px; margin: 0 auto; border-radius: 12px; border: 1px solid #1e293b;">
          <h2 style="color: #38bdf8; margin-top: 0;">⚡ New Proposal Alert for Admin</h2>
          <div style="background-color: #0f172a; padding: 20px; border-radius: 8px; border: 1px solid #334155; margin: 20px 0;">
            <p><strong>Tracking ID:</strong> <span style="color: #38bdf8; font-family: monospace;">${orderData.id}</span></p>
            <p><strong>Client Name:</strong> ${orderData.name}</p>
            <p><strong>Corporate Email:</strong> ${orderData.email}</p>
            <p><strong>Phone / Hotline:</strong> ${orderData.phone || 'N/A'}</p>
            <p><strong>Service Area:</strong> ${orderData.service}</p>
            <p><strong>Scale:</strong> ${orderData.scale || 'Enterprise'}</p>
            <p><strong>Estimated Budget:</strong> <span style="color: #34d399;">${orderData.budget}</span></p>
            <p><strong>Project Requirements:</strong></p>
            <blockquote style="border-left: 3px solid #38bdf8; padding-left: 10px; color: #cbd5e1; margin: 10px 0;">
              ${orderData.details}
            </blockquote>
          </div>
          <p style="color: #94a3b8; font-size: 12px;">This message was automatically generated by Lyntrix Enterprise Architecture Sentinel.</p>
        </div>
      `;
    } else {
      // Client order confirmation
      recipient = orderData.email;
      subject = `✅ [Proposal Received & Accepted] Lyntrix IT Services: ${orderData.id} - ${orderData.service}`;
      htmlContent = `
        <div style="font-family: Arial, sans-serif; background-color: #07090e; color: #f1f5f9; padding: 30px; max-width: 600px; margin: 0 auto; border-radius: 12px; border: 1px solid #1e293b;">
          <h2 style="color: #38bdf8; margin-top: 0;">Proposal Received & Scoped</h2>
          <p>Dear ${orderData.name},</p>
          <p>Thank you for choosing <strong>Lyntrix IT Services</strong>. Your proposal for <strong>${orderData.service}</strong> has been logged into our Cloud DB and assigned to our Senior Solutions Architecture Team.</p>
          
          <div style="background-color: #0f172a; padding: 20px; border-radius: 8px; border: 1px solid #334155; margin: 20px 0;">
            <p><strong>Proposal Tracking ID:</strong> <span style="color: #38bdf8; font-family: monospace;">${orderData.id}</span></p>
            <p><strong>Selected Service:</strong> ${orderData.service}</p>
            <p><strong>Estimated Budget:</strong> <span style="color: #34d399;">${orderData.budget}</span></p>
            <p><strong>Status:</strong> <span style="color: #38bdf8;">Order Accepted & Discovery Scoped</span></p>
          </div>

          <p>Our engineering lead will reach out within 24 hours to coordinate discovery and deployment milestones.</p>
          <p style="color: #64748b; font-size: 11px; margin-top: 30px;">
            Lyntrix IT Services • <a href="https://dilnethmadushanka.online" style="color: #38bdf8;">dilnethmadushanka.online</a>
          </p>
        </div>
      `;
    }

    const info = await transporter.sendMail({
      from: `"Lyntrix Orders" <${gmailUser}>`,
      to: recipient,
      subject: subject,
      html: htmlContent
    });

    return res.status(200).json({
      success: true,
      messageId: info.messageId,
      recipient,
      timestamp: new Date().toLocaleTimeString()
    });
  } catch (err) {
    console.error('Nodemailer Email Error:', err);
    return res.status(500).json({
      error: 'Failed to send email via Nodemailer',
      details: err.message
    });
  }
}
